# Generated by Django 4.2.20 on 2025-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message text')),
                ('is_message_artificial', models.BooleanField(help_text='Is the message a user prompt or AI generated')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='Date Last Modified')),
            ],
        ),
    ]
